### ISSUE TITLE
HomeWork and group assignment

### ISSUE THREAD

**Issue by benivd** [benivd/DevOps-School#29]
Hi Liora,
According to the last meeting and the homework that you gave us.
Beacuse it is difficult to work in group (like shay said over and over) and in the last assignment 
that you gave us my assignment relys on shay assignment but until today
he didn't upload anything to github ( and i can't wait forever... I have a job and other things to do )
I want to ask if it's ok to do all the homework(all the assignment) like i did today?
And in the future if you can give us homework that doesn't rely on the another assignment.
Thanks,
Beni

**Comment by lioramilbaum** [comment]
Beni,

I totally understand. I have to rethink this delicate situation and make
some decisions.
You have my approval to do the whole task.

Liora

On Wed, Feb 11, 2015 at 4:24 PM, benivd <notifications@github.com> wrote:

> Hi Liora,
> According to the last meeting and the homework that you give us.
> Beacuse it difficult to work in group (like shay said over and over) and
> in the last assignment
> that you give us my assignment rely on shay assignment but until today
> he didn't upload anything to github ( and i can't wait forever... I have a
> job and other things to do )
> I want to ask if it's ok to do all the homework(all the assignment) like i
> do today?
> And in the future if you can give us homework that don't rely on the other
> assignment.
> Thanks,
> Beni
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benivd/DevOps-School/issues/29>.
>



-- 
Liora Milbaum
DevOps & ALM Evangelist
+972.54.656.0051
liora@lmb.co.il

For more info about me, read my blog:
http://lioramilbaum.wordpress.com/

**Comment by benivd** [comment]
Ok...
Thanks
